### ISSUE TITLE
Feature 5: Users can see their top tracks + artists in the last 6 months.

### ISSUE THREAD

**Issue by justintaeson** [justintaeson/visualify#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can see their top tracks + artists in the last 6 months.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will have the ability to filter and see their most listened to tracks and artists in the last 6 months.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Test with HTTPie to make sure data is coming through properly.
- [x] Create a route for getting the top tracks + artists in the last 6 months in an organized way.

### ⚡ Client

- [x] Update the tracks component to handle when a user clicks on the 6 month filter button.
- [x] Send a GET request to the server for 6 months track data.
- [x] Update the artists component to handle when a user clicks on the 6 month filter button.
- [x] Send a GET request to the server for 6 months artist data.

### 🧑‍⚕️ Clean Up

- [x] Remove all console logs.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
